force-app/main/default/objects/AZSC_Constant__mdt/AZSC_Constant__mdt.object-meta.xml
<CustomObject>
    <label>AZSC Constant</label>
    <pluralLabel>AZSC_Constants</pluralLabel>
</CustomObject>

force-app/main/default/objects/BusinessLicense/fields/Late_Fee_From__c.field-meta.xml
<CustomField>
    <fullName>Late_Fee_From__c</fullName>
    <formula>ADDMONTHS( DATE(
    YEAR( DATEVALUE(PeriodEnd) ), MONTH( DATEVALUE (PeriodEnd) ), 1
), (VALUE( RegulatoryAuthorizationType.Late_Fee_Duration__c ) - 1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Late Fee From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case_Relationship__c/Case_Relationship__c.object-meta.xml
<CustomObject>
    <label>Application Participant</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Application Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Relationship__c/fields/Business_License__c.field-meta.xml
<CustomField>
    <fullName>Business_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business License</label>
    <referenceTo>BusinessLicense</referenceTo>
    <relationshipLabel>Application Participants</relationshipLabel>
    <relationshipName>Application_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Relationship__c/fields/Do_not_Send_Sub_Application__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Send_Sub_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Send Sub Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Relationship__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <formula>IF( ISBLANK(Person_Account__r.PersonContact.Email),  Person_Account__r.POC_Email__c , Person_Account__r.PersonContact.Email)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Relationship__c/fields/Person_Account__c.field-meta.xml
<CustomField>
    <fullName>Person_Account__c</fullName>
    <label>Participant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Application Participants</relationshipLabel>
    <relationshipName>Case_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RegulatoryAuthorizationType/fields/Expiration_Day__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Day__c</fullName>
    <label>Expiration Day</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Expiration_Month__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RegulatoryAuthorizationType/fields/Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Month__c</fullName>
    <label>Expiration Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AZSC_ScheduleEmailAlerts.cls
/**
* @File Name : AZSC_ScheduleEmailAlerts.cls
* @Description :
* @Author : Oliver
* @Last Modified By : Oliver
* @Last Modified On : September 24, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 24, 2025 |   | Initial Version
**/
 
global class AZSC_ScheduleEmailAlerts implements Schedulable, Database.Batchable<sObject> {
    public String query;
    public Map<String,Object> paramKeytoValue;
	public AZSC_ScheduleEmailAlerts(String query, Map<String,Object> paramKeytoValue) {
        this.query = query;
		this.paramKeytoValue = paramKeytoValue;
    }
	global void execute(SchedulableContext sc) {
		//Business License - Certificatie 90 Day Renewal Reminder
        //Run Everyday at 4am
        /*Integer dayNum = 90;
        System.schedule('ABS Renewal 90 day Reminder Job', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'ABS_Renewal_90_Day_Reminder_1758696730521', 'sObjectName' => 'BusinessLicense', 'senderEmail' => 'ABS Email'}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'ABS_Renewal_90_Day_Reminder_1758696730521', 'sObjectName' => 'BusinessLicense', 'senderEmail' => 'ABS Email'}));*/
        
        //Business License - Certificatie 30 Day Renewal Reminder
        //Run Everyday at 4am
        /*Integer dayNum = 30;
        System.schedule('ABS Renewal 30 day Reminder Job', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'ABS_Renewal_30_Day_Reminder_1758696996570', 'sObjectName' => 'BusinessLicense', 'senderEmail' => 'ABS Email'}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'ABS_Renewal_30_Day_Reminder_1758696996570', 'sObjectName' => 'BusinessLicense', 'senderEmail' => 'ABS Email'}));*/
        
        //Business License - Licensing CRI Renewal 7 Day Reminder Email
        //Run Everyday at 4am
        /*Integer dayNum = 7;
        System.schedule('Licensing CRI Renewal 7 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'Licensing_CRI_Renewal_7_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'Licensing_CRI_Renewal_7_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
        
        //Business License - Licensing CR Renewal 60 Day Reminder Email
        //Run Everyday at 4am
        /*Integer dayNum = 60;
        System.schedule('Licensing CR Renewal 60 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_60_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_60_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
        
        // Business License - CR Renewal Second Month Reminder Email
        // Runs everyday at 4am
        // Integer dayNum = 28;
        /*System.schedule('CR Renewal Second Month Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
        //Business License - LCR Renewal Second Month 14 Day Reminder Email
        //Run Everyday at 4am
        /*Integer dayNum = 14;
        System.schedule('LCR Renewal Second Month 14 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_14_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_14_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
        //Business License - CR Renewal Second Month 7 Day Reminder Email
        //Run Everyday at 4am
        /*Integer dayNum = 7;
        System.schedule('CR Renewal Second Month 7 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_7_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (PeriodEnd > NEXT_N_DAYS:' + (dayNum - 2) + ' AND PeriodEnd = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_7_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
   
        //Business License - CR Renewal Second Month 1 Day Reminder Email
        //Run Everyday at 4am
       /* System.schedule('CR Renewal Second Month 1 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c + '\' AND PeriodEnd = TODAY', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_1_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c + '\' AND PeriodEnd = TODAY', new Map<String,Object>{'templateName' => 'CR_Renewal_Second_Month_1_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
   
         //Business License - CR Renewal First Month 14 Day Reminder Email
        //Run Everyday at 4am
        /*Integer dayNum = 14;
        System.schedule('CR Renewal First Month 14 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (Late_Fee_From__c > NEXT_N_DAYS:' + (dayNum - 2) + ' AND Late_Fee_From__c = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_First_Month_14_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (Late_Fee_From__c > NEXT_N_DAYS:' + (dayNum - 2) + ' AND Late_Fee_From__c = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_First_Month_14_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
         //Business License - CR Renewal First Month 7 Day Reminder Email
        //Run Everyday at 4am
        /*Integer dayNum = 7;
        System.schedule('CR Renewal First Month 7 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (Late_Fee_From__c > NEXT_N_DAYS:' + (dayNum - 2) + ' AND Late_Fee_From__c = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_First_Month_7_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c+'\' AND (Late_Fee_From__c > NEXT_N_DAYS:' + (dayNum - 2) + ' AND Late_Fee_From__c = NEXT_N_DAYS:' + (dayNum - 1) + ')', new Map<String,Object>{'templateName' => 'CR_Renewal_First_Month_7_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
         //Business License - CR Renewal First Month 1 Day Reminder Email
        //Run Everyday at 4am
        /*System.schedule('CR Renewal First Month 1 Day Reminder Email', '0 0 4 1/1 * ? *', new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c + '\' AND Late_Fee_From__c = TODAY', new Map<String,Object>{'templateName' => 'CR_Renewal_First_Month_1_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));
        Database.executeBatch(new AZSC_ScheduleEmailAlerts('SELECT Id FROM BusinessLicense WHERE Status = \''+AZSC_Constant__mdt.getInstance('LicenseStatusRenewalPending').Value__c + '\' AND Late_Fee_From__c = TODAY', new Map<String,Object>{'templateName' => 'CR_Renewal_First_Month_1_Day_Reminder_Email', 'sObjectName' => 'BusinessLicense', 'senderEmail' => AZSC_Constant__mdt.getInstance('OrgWideEmail').Value__c}));*/
        
    	Database.executeBatch(new AZSC_ScheduleEmailAlerts(query, paramKeytoValue));
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> records) {
        List<sObject> createSObjs = new List<sObject>();
		List<EmailTemplate> templates = [SELECT Id,Subject,HtmlValue,Body FROM EmailTemplate WHERE DeveloperName =: ''+paramKeytoValue.get('templateName')];
		Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
        List<OrgWideEmailAddress> orgWideEmails = [SELECT Id,Address,DisplayName,Purpose,IsVerified,IsAllowAllProfiles FROM OrgWideEmailAddress WHERE IsVerified = true AND DisplayName =: ''+paramKeytoValue.get('senderEmail')];
        if(''+paramKeytoValue.get('sObjectName') == 'BusinessLicense') {
            Set<String> keys = new Set<String>();
            If(paramKeytoValue.get('senderEmail') == 'ABS Email') {
                for(Case_Relationship__c participant : [SELECT Id,Business_License__c,Email_Address__c,Person_Account__r.PersonContactId FROM Case_Relationship__c WHERE Business_License__c IN: records AND Role__c IN ('Designated Principal', 'Compliance Lawyer') AND Do_not_Send_Sub_Application__c = false]) {
                    if(!keys.contains(participant.Business_License__c+''+participant.Email_Address__c)) {
                        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                        message.setTargetObjectId(participant.Person_Account__r.PersonContactId);
                        if(!templates.isEmpty())
                            message.setTemplateId(templates[0].Id);
                        message.setToAddresses(new List<String>{participant.Email_Address__c});
                        message.setSaveAsActivity(false);          
                        message.setWhatId(participant.Business_License__c);
                        if(!orgWideEmails.isEmpty())
                            message.setOrgWideEmailAddressId(orgWideEmails[0].Id);
                        messages.add(message);
                    }
                    else
                        keys.add(participant.Business_License__c+''+participant.Email_Address__c);
                }
            }
            else {
                for(BusinessLicense Business:[Select Id,ContactId,contact.Email,RegulatoryAuthorizationType.name,RegulatoryAuthorizationType.Expiration_Day__c,RegulatoryAuthorizationType.Expiration_Month__c From BusinessLicense Where Id In :records]) {
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    message.setTargetObjectId(Business.ContactId);
                    if(!templates.isEmpty())
                        message.setTemplateId(templates[0].Id);
                    message.setSaveAsActivity(true);          
                    message.setWhatId(Business.Id); 
                    if(!orgWideEmails.isEmpty())
                    message.setOrgWideEmailAddressId(orgWideEmails[0].Id);
                    //message= AZSC_EmailTemplateMerger.mergeContent(message, templates[0], Business);
                    messages.add(message);
                }
            }
        }
        /*for(sObject sObj : records) {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setTargetObjectId((String)sObj.get('ContactId'));
            if(!templates.isEmpty())
                message.setTemplateId(templates[0].Id);
            message.setToAddresses(new List<String>{(String)sObj.getSobject('Contact').get('Email')});
            message.setSaveAsActivity(false);          
            message.setWhatId((String)sObj.get('Id'));
            if(!orgWideEmails.isEmpty())
                message.setOrgWideEmailAddressId(orgWideEmails[0].Id);
            messages.add(message);
        }*/
        if(!messages.isEmpty() && !Test.isRunningTest())
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
    }
    global void finish(Database.BatchableContext BC) {}
}